[build]
  command = "pnpm --filter @workspace/eventura run build"
  publish = "artifacts/eventura/dist/public"

[build.environment]
  NODE_VERSION = "20"
  PNPM_FLAGS = "--no-frozen-lockfile"
  VITE_CLERK_PUBLISHABLE_KEY = "pk_test_YW1wbGUtZ2Vja28tNzQ2LmNsZXJrLmFjY291bnRzLmRldiQ"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
